// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import EmojiController from "./emoji_controller"
application.register("emoji", EmojiController)

import FormStepsController from "./form_steps_controller"
application.register("form-steps", FormStepsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PriceCalculatorController from "./price_calculator_controller"
application.register("price-calculator", PriceCalculatorController)

import TimePickerController from "./time_picker_controller"
application.register("time-picker", TimePickerController)

import TurboStreamController from "./turbo_stream_controller"
application.register("turbo-stream", TurboStreamController)
